//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZdravoCorp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZdravoCorp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action doesnt exist in data base.
        /// </summary>
        public static string ActionDoesntExist {
            get {
                return ResourceManager.GetString("ActionDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Equipment.
        /// </summary>
        public static string Add_Equipment {
            get {
                return ResourceManager.GetString("Add Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Equipment Type.
        /// </summary>
        public static string Add_Equipment_Type {
            get {
                return ResourceManager.GetString("Add Equipment Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Medication.
        /// </summary>
        public static string Add_Medication {
            get {
                return ResourceManager.GetString("Add Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Medication Type.
        /// </summary>
        public static string Add_Medication_Type {
            get {
                return ResourceManager.GetString("Add Medication Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Room.
        /// </summary>
        public static string Add_Room {
            get {
                return ResourceManager.GetString("Add Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Room Type.
        /// </summary>
        public static string Add_Room_Type {
            get {
                return ResourceManager.GetString("Add Room Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anamnesis doesnt exist.
        /// </summary>
        public static string AnamnesisDoesntExist {
            get {
                return ResourceManager.GetString("AnamnesisDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anamnesis already exists.
        /// </summary>
        public static string AnamnesisExists {
            get {
                return ResourceManager.GetString("AnamnesisExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Medication.
        /// </summary>
        public static string Change_Medication {
            get {
                return ResourceManager.GetString("Change Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Renovation.
        /// </summary>
        public static string Change_Renovation {
            get {
                return ResourceManager.GetString("Change Renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Reservation.
        /// </summary>
        public static string Change_Reservation {
            get {
                return ResourceManager.GetString("Change Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine.
        /// </summary>
        public static string Combine {
            get {
                return ResourceManager.GetString("Combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine Rooms.
        /// </summary>
        public static string Combine_Rooms {
            get {
                return ResourceManager.GetString("Combine Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine with.
        /// </summary>
        public static string Combine_with {
            get {
                return ResourceManager.GetString("Combine with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PDF.
        /// </summary>
        public static string Create_PDF {
            get {
                return ResourceManager.GetString("Create PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Room.
        /// </summary>
        public static string Current_Room {
            get {
                return ResourceManager.GetString("Current Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily number of users.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days in week.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Replacement.
        /// </summary>
        public static string Delete_Replacement {
            get {
                return ResourceManager.GetString("Delete Replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation Code.
        /// </summary>
        public static string Designation_Code {
            get {
                return ResourceManager.GetString("Designation Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation for new Room.
        /// </summary>
        public static string Designation_for_new_Room {
            get {
                return ResourceManager.GetString("Designation for new Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposable.
        /// </summary>
        public static string Disposable {
            get {
                return ResourceManager.GetString("Disposable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor type doesnt exists.
        /// </summary>
        public static string DoctorTypeDoesntExists {
            get {
                return ResourceManager.GetString("DoctorTypeDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor type already exists.
        /// </summary>
        public static string DoctorTypeExists {
            get {
                return ResourceManager.GetString("DoctorTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employess.
        /// </summary>
        public static string Employess {
            get {
                return ResourceManager.GetString("Employess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string End_Date {
            get {
                return ResourceManager.GetString("End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Type.
        /// </summary>
        public static string Equipment_Type {
            get {
                return ResourceManager.GetString("Equipment Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment doesnt exist in database.
        /// </summary>
        public static string EquipmentDoesntExist {
            get {
                return ResourceManager.GetString("EquipmentDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Type doesnt exist in database.
        /// </summary>
        public static string EquipmentDoesntExists {
            get {
                return ResourceManager.GetString("EquipmentDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment name already exists.
        /// </summary>
        public static string EquipmentNameExists {
            get {
                return ResourceManager.GetString("EquipmentNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient already exists.
        /// </summary>
        public static string IngredientDoesExist {
            get {
                return ResourceManager.GetString("IngredientDoesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient doesnt exist.
        /// </summary>
        public static string IngredientDoesntExist {
            get {
                return ResourceManager.GetString("IngredientDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Renovating Now.
        /// </summary>
        public static string Is_Renovating_Now {
            get {
                return ResourceManager.GetString("Is Renovating Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max surface.
        /// </summary>
        public static string Max_surface {
            get {
                return ResourceManager.GetString("Max surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication.
        /// </summary>
        public static string Medication {
            get {
                return ResourceManager.GetString("Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication Type.
        /// </summary>
        public static string Medication_Type {
            get {
                return ResourceManager.GetString("Medication Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication Types.
        /// </summary>
        public static string Medication_Types {
            get {
                return ResourceManager.GetString("Medication Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication type does exist.
        /// </summary>
        public static string MedicationTypeDoesExist {
            get {
                return ResourceManager.GetString("MedicationTypeDoesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication type doesnt exist.
        /// </summary>
        public static string MedicationTypeDoesntExist {
            get {
                return ResourceManager.GetString("MedicationTypeDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        public static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly number of users.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Request.
        /// </summary>
        public static string Pending_Request {
            get {
                return ResourceManager.GetString("Pending Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Request.
        /// </summary>
        public static string Rejected_Request {
            get {
                return ResourceManager.GetString("Rejected Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovate.
        /// </summary>
        public static string Renovate {
            get {
                return ResourceManager.GetString("Renovate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovate Room.
        /// </summary>
        public static string Renovate_Room {
            get {
                return ResourceManager.GetString("Renovate Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovated.
        /// </summary>
        public static string Renovated {
            get {
                return ResourceManager.GetString("Renovated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovations.
        /// </summary>
        public static string Renovations {
            get {
                return ResourceManager.GetString("Renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement.
        /// </summary>
        public static string Replacement {
            get {
                return ResourceManager.GetString("Replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        public static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type.
        /// </summary>
        public static string Room_Type {
            get {
                return ResourceManager.GetString("Room Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Designation Code already exists.
        /// </summary>
        public static string RoomDesignationExists {
            get {
                return ResourceManager.GetString("RoomDesignationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room doesnt exist in database.
        /// </summary>
        public static string RoomIdDoesntExist {
            get {
                return ResourceManager.GetString("RoomIdDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type already exists.
        /// </summary>
        public static string RoomTypeAlreadyExists {
            get {
                return ResourceManager.GetString("RoomTypeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type doesnt exist in database.
        /// </summary>
        public static string RoomTypeDoesntExists {
            get {
                return ResourceManager.GetString("RoomTypeDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Room.
        /// </summary>
        public static string Selected_Room {
            get {
                return ResourceManager.GetString("Selected Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Room.
        /// </summary>
        public static string Split_Room {
            get {
                return ResourceManager.GetString("Split Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Start_Date {
            get {
                return ResourceManager.GetString("Start Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string Start_Time {
            get {
                return ResourceManager.GetString("Start Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Area.
        /// </summary>
        public static string Surface_Area {
            get {
                return ResourceManager.GetString("Surface Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report of Survey.
        /// </summary>
        public static string Survey {
            get {
                return ResourceManager.GetString("Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        public static string Surveys {
            get {
                return ResourceManager.GetString("Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesnt exist.
        /// </summary>
        public static string UserDoesntExist {
            get {
                return ResourceManager.GetString("UserDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Survey.
        /// </summary>
        public static string ViewSurvey {
            get {
                return ResourceManager.GetString("ViewSurvey", resourceCulture);
            }
        }
    }
}
